version: 0.2
phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in the Amazon ECR
      - aws --version
      - docker --version
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 113724943410.dkr.ecr.ap-northeast-1.amazonaws.com
      - REPOSITORY_URI = 113724943410.dkr.ecr.ap-northeast-1.amazonaws.com/lambada-support-registery
      - COMMIT HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image....
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing the docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definations file....
      - printf '[{"name":"lambada-service","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imageDefinations.json
      - cat imageDefinations.json
artifacts:
  files:
    - imageDefinations.json
    - target/lambada-service-0.0.1-SNAPSHOT-aws.jar
